CREATE TABLE chatsession (
    chatid NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userid NUMBER NOT NULL,
    name VARCHAR2(120) NOT NULL,
    datestart TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    dateupdated TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_chatsession_user FOREIGN KEY (userid) REFERENCES users(userid)
);

CREATE TABLE chathistory (
    chathistoryid NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chatid NUMBER NOT NULL,
    promptorresponse NUMBER(1) NOT NULL,
    content CLOB NOT NULL,
    datecreated TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_chathistory_session FOREIGN KEY (chatid) REFERENCES chatsession(chatid),
    CONSTRAINT ck_chathistory_prompt CHECK (promptorresponse IN (0, 1))
);

CREATE INDEX idx_chatsession_user_updated ON chatsession(userid, dateupdated);
CREATE INDEX idx_chathistory_chat_created ON chathistory(chatid, datecreated);
